### PR TITLE
Update GridPawn.cpp

### PR DESCRIPTION
**Pull request by Miru302**
Default Height is (44*2), but since the pivot of the capsule is in center of the component, Z offset should be just above Half Height (44). I think 50 sounds like a good number :)

### CODE REVIEW

**Comment by Miru302** [comment]
Without this adjustment, all capsules look way above the grid. I was not sure if it's intended or it behaves strangely only on my end, but it was good excuse for me to start doing something :)
P.S. I'm still learning the ropes, and it's my first pull request ever. Excited!

Edit: Looks like arrow should be adjusted too, since its initializes at xyz 0 location now.

**Comment by larsjsol** [comment]
Hi @Miru302! 

You are right that putting the capsule at height 100 does not put it "just above the floor" as stated in the comment. However, when I started using NavMesh in my own projects, often with a human-like skeletal mesh, I found that having the capsule too close to the floor would often cause it to collide with small items that were not meant to block the path. Putting the capsule higher up meant that the pawns could traverse rougher terrain.

Unfortunately, I did not update the comment when changing the default height.

You are defiantly right about the arrow component. It should be moved up a bit. 

I you feel like it I would be happy to accept an updated pull request with an updated comment for the capsule component and that moves the arrow component. If not, I will do it myself at some point :)

Anyway, thank you for you contribution!

**Comment by Miru302** [comment]
Thank you, @larsjsol!
I have updated pull request just as you said~ :)

Now I see why the capsule location was set to be that high. Although isn't the usual workflow is to adjust collisions settings so floor's mesh component and capsule don't collide with each other? I guess it's may depend on project though. Or just reducing steps to setup the plugin. :)

**Comment by larsjsol** [comment]
Thank you for your contribution.

> Although isn't the usual workflow is to adjust collisions settings so floor's mesh component and capsule don't collide with each other?
Yes it is :) 

NavGrid makes a collision trace with the capsule to determine if a tile is occupied by another pawn or some other obstacle. An upside to this approach is that it simplifies level design as you can just place obstacles on the grid and the pawns will then have to move around it.  The downside of this approach is that you might have to tune the size of the capsule so it fits your pawns and game. Purely decorative props should still be set to no collision.

**Comment by Miru302** [comment]
Ah, it makes perfect sense now.
And thank you for the merge! Those may be small changes but it really feels good, haha :)
This is a great plugin, hope I can help you in more meaningfull way in the future. GoodLuck~

**Pull request merged**
